name: Deploy MultiDocker
on:
  push:
    branches:
      - master # check your repo, your default branch might be master!

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - run: docker build -t shivisis/react-test -f ./client/Dockerfile.dev ./client
      - run: docker run -e CI=true shivisis/react-test npm test

      - run: docker build -t shivisis/multi-client ./client
      - run: docker build -t shivisis/multi-nginx ./nginx
      - run: docker build -t shivisis/multi-server ./server
      - run: docker build -t eu-west-1/mushivisislti-worker ./worker

      - run: docker push shivisis/multi-client
      - run: docker push shivisis/multi-nginx
      - run: docker push shivisis/multi-server
      - run: docker push shivisis/multi-worker

      - name: Generate deployment package
        run: zip -r deploy.zip . -x '*.git*'

      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v18
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
          application_name: multi-container-docker
          environment_name: multi-container-docker-env
          existing_bucket_name: elasticbeanstalk-ap-south-1-085031185171
          region: ap-south-1
          version_label: ${{ github.sha }}
          deployment_package: deploy.zip
